name: speech_prompt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - anyio=2.2.0=py39h06a4308_1
  - argon2-cffi=20.1.0=py39h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py39hf3d152e_1
  - cryptography=35.0.0=py39hd23ed53_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.4.1=py39h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39h06a4308_0
  - fastbpe=0.1.0=py39h1a9c180_4
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.8.1=py39h06a4308_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.4.1=py39h06a4308_1
  - ipython=7.29.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py39h06a4308_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py39h06a4308_0
  - jupyter_server=1.4.1=py39h06a4308_0
  - jupyterlab=3.2.1=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.8.2=pyhd3eb1b0_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py39h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.4.5=py39h06a4308_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py39h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.2.1=py39h295c915_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sniffio=1.2.0=py39h06a4308_1
  - sqlite=3.36.0=hc218d9a_0
  - terminado=0.9.4=py39h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.15.0
    - amfm-decompy==1.0.11
    - antlr4-python3-runtime==4.8
    - bitarray==2.3.4
    - black==22.3.0
    - cachetools==4.2.4
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - click==8.0.3
    - colorama==0.4.4
    - cycler==0.11.0
    - cython==0.29.24
    - editdistance==0.6.0
    - ffmpeg==1.4
    - flake8==4.0.1
    - google-auth==2.3.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.41.1
    - hydra-core==1.0.7
    - jiwer==2.3.0
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - mccabe==0.6.1
    - mypy-extensions==0.4.3
    - numpy==1.22.2
    - oauthlib==3.1.1
    - omegaconf==2.0.6
    - pathspec==0.9.0
    - platformdirs==2.4.0
    - portalocker==2.3.2
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - python-levenshtein==0.12.2
    - pyyaml==6.0
    - regex==2021.11.2
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacrebleu==2.0.0
    - sacremoses==0.0.46
    - scikit-learn==1.0.1
    - scipy==1.7.1
    - soundfile==0.10.3.post1
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4.1
    - threadpoolctl==3.0.0
    - tomli==1.2.2
    - torch==1.10.2
    - torchsummary==1.5.1
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.2
